import 'dotenv/config';

import prisma from '../src/lib/prisma';

async function main() {
  console.log('Clearing existing data...');
  await prisma.cartItem.deleteMany({});
  await prisma.cart.deleteMany({});
  await prisma.mealPlanProduk.deleteMany({});
  await prisma.orderItem.deleteMany({});
  await prisma.produkMakanan.deleteMany({});
  await prisma.mealPlan.deleteMany({});
  await prisma.riwayatAnalisis.deleteMany({});
  await prisma.profilKesehatan.deleteMany({});

  console.log('Seeding products...');
  const mockProducts = [
    {
      id: '1',
      namaProduk: 'Organic Brown Rice',
      kategori: 'Grains',
      gambar: '🌾',
      nilaiGizi: {
        calories: 110,
        protein: 3,
        fat: 1,
        carbs: 23,
        sugars: 0,
        sodium: 5,
        cholesterol: 0,
        tags: ['Low Sodium', 'Whole Grain'],
        foodType: 'carb',
        allergens: [],
        ingredients: ['brown rice'],
        cookingMethod: 'boiled',
        spicyLevel: 0,
      },
      harga: 25000,
      stok: 100,
    },
    {
      id: '2',
      namaProduk: 'Fresh Chicken Breast',
      kategori: 'Meat',
      gambar: '🍗',
      nilaiGizi: {
        calories: 165,
        protein: 31,
        fat: 4,
        carbs: 0,
        sugars: 0,
        sodium: 74,
        cholesterol: 85,
        tags: ['High Protein'],
        foodType: 'protein',
        allergens: [],
        ingredients: ['chicken'],
        cookingMethod: 'grilled',
        spicyLevel: 0,
      },
      harga: 45000,
      stok: 100,
    },
    {
      id: '3',
      namaProduk: 'Greek Yogurt',
      kategori: 'Dairy',
      gambar: '🥛',
      nilaiGizi: {
        calories: 59,
        protein: 10,
        fat: 0,
        carbs: 4,
        sugars: 3,
        sodium: 36,
        cholesterol: 5,
        tags: ['Low Fat', 'Probiotic'],
        foodType: 'dairy',
        allergens: ['milk'],
        ingredients: ['yogurt'],
        cookingMethod: 'none',
        spicyLevel: 0,
      },
      harga: 20000,
      stok: 100,
    },
    {
      id: '4',
      namaProduk: 'Salmon Fillet',
      kategori: 'Seafood',
      gambar: '🐟',
      nilaiGizi: {
        calories: 208,
        protein: 22,
        fat: 13,
        carbs: 0,
        sugars: 0,
        sodium: 59,
        cholesterol: 55,
        tags: ['Omega-3', 'High Protein'],
        foodType: 'protein',
        allergens: ['fish'],
        ingredients: ['salmon'],
        cookingMethod: 'grilled',
        spicyLevel: 0,
      },
      harga: 75000,
      stok: 100,
    },
    {
      id: '5',
      namaProduk: 'Sweet Potato',
      kategori: 'Vegetables',
      gambar: '🍠',
      nilaiGizi: {
        calories: 86,
        protein: 2,
        fat: 0,
        carbs: 20,
        sugars: 4,
        sodium: 55,
        cholesterol: 0,
        tags: ['High Fiber', 'Low Fat'],
        foodType: 'vegetable',
        allergens: [],
        ingredients: ['sweet potato'],
        cookingMethod: 'boiled',
        spicyLevel: 0,
      },
      harga: 15000,
      stok: 100,
    },
    {
      id: '6',
      namaProduk: 'Honey',
      kategori: 'Sweeteners',
      gambar: '🍯',
      nilaiGizi: {
        calories: 64,
        protein: 0,
        fat: 0,
        carbs: 17,
        sugars: 17,
        sodium: 1,
        cholesterol: 0,
        tags: ['Natural Sugar', 'High Sugar'],
        foodType: 'sweetener',
        allergens: [],
        ingredients: ['honey'],
        cookingMethod: 'none',
        spicyLevel: 0,
      },
      harga: 30000,
      stok: 100,
    },
    {
      id: '7',
      namaProduk: 'Avocado',
      kategori: 'Fruits',
      gambar: '🥑',
      nilaiGizi: {
        calories: 160,
        protein: 2,
        fat: 15,
        carbs: 9,
        sugars: 1,
        sodium: 7,
        cholesterol: 0,
        tags: ['Healthy Fats', 'High Fiber'],
        foodType: 'fat',
        allergens: [],
        ingredients: ['avocado'],
        cookingMethod: 'none',
        spicyLevel: 0,
      },
      harga: 25000,
      stok: 100,
    },
    {
      id: '8',
      namaProduk: 'Almonds',
      kategori: 'Nuts',
      gambar: '🥜',
      nilaiGizi: {
        calories: 579,
        protein: 21,
        fat: 50,
        carbs: 22,
        sugars: 4,
        sodium: 1,
        cholesterol: 0,
        tags: ['Vitamin E', 'Healthy Fats'],
        foodType: 'fat',
        allergens: ['tree nuts'],
        ingredients: ['almonds'],
        cookingMethod: 'none',
        spicyLevel: 0,
      },
      harga: 65000,
      stok: 100,
    },
    {
      id: '9',
      namaProduk: 'Spinach',
      kategori: 'Vegetables',
      gambar: '🥬',
      nilaiGizi: {
        calories: 23,
        protein: 3,
        fat: 0,
        carbs: 4,
        sugars: 0,
        sodium: 79,
        cholesterol: 0,
        tags: ['Iron', 'Vitamins'],
        foodType: 'vegetable',
        allergens: [],
        ingredients: ['spinach'],
        cookingMethod: 'none',
        spicyLevel: 0,
      },
      harga: 10000,
      stok: 100,
    },
    {
      id: '10',
      namaProduk: 'Tofu',
      kategori: 'Plant Protein',
      gambar: '🧊',
      nilaiGizi: {
        calories: 76,
        protein: 8,
        fat: 5,
        carbs: 2,
        sugars: 0,
        sodium: 7,
        cholesterol: 0,
        tags: ['Calcium', 'Vegan'],
        foodType: 'protein',
        allergens: ['soy'],
        ingredients: ['tofu'],
        cookingMethod: 'none',
        spicyLevel: 0,
      },
      harga: 8000,
      stok: 100,
    },
    {
      id: '11',
      namaProduk: 'Tempeh',
      kategori: 'Plant Protein',
      gambar: '🧆',
      nilaiGizi: {
        calories: 193,
        protein: 19,
        fat: 11,
        carbs: 9,
        sugars: 0,
        sodium: 9,
        cholesterol: 0,
        tags: ['Fermented', 'High Protein'],
        foodType: 'protein',
        allergens: ['soy'],
        ingredients: ['tempeh'],
        cookingMethod: 'none',
        spicyLevel: 0,
      },
      harga: 10000,
      stok: 100,
    },
    {
      id: '12',
      namaProduk: 'Eggs',
      kategori: 'Dairy/Egg',
      gambar: '🥚',
      nilaiGizi: {
        calories: 70,
        protein: 6,
        fat: 5,
        carbs: 1,
        sugars: 1,
        sodium: 70,
        cholesterol: 186,
        tags: ['Complete Protein', 'Choline'],
        foodType: 'protein',
        allergens: ['egg'],
        ingredients: ['egg'],
        cookingMethod: 'boiled',
        spicyLevel: 0,
      },
      harga: 28000,
      stok: 100,
    },
    {
      id: '13',
      namaProduk: 'Oatmeal',
      kategori: 'Grains',
      gambar: '🥣',
      nilaiGizi: {
        calories: 150,
        protein: 5,
        fat: 3,
        carbs: 27,
        sugars: 1,
        sodium: 0,
        cholesterol: 0,
        tags: ['Beta Glucan', 'High Fiber'],
        foodType: 'carb',
        allergens: [],
        ingredients: ['oats'],
        cookingMethod: 'boiled',
        spicyLevel: 0,
      },
      harga: 32000,
      stok: 100,
    },
    {
      id: '14',
      namaProduk: 'Extra Virgin Olive Oil',
      kategori: 'Oils',
      gambar: '🫒',
      nilaiGizi: {
        calories: 884,
        protein: 0,
        fat: 100,
        carbs: 0,
        sugars: 0,
        sodium: 2,
        cholesterol: 0,
        tags: ['Heart Healthy', 'Antioxidants'],
        foodType: 'fat',
        allergens: [],
        ingredients: ['olive oil'],
        cookingMethod: 'none',
        spicyLevel: 0,
      },
      harga: 95000,
      stok: 100,
    },
    {
      id: '15',
      namaProduk: 'Dark Chocolate (70%)',
      kategori: 'Snacks',
      gambar: '🍫',
      nilaiGizi: {
        calories: 598,
        protein: 8,
        fat: 43,
        carbs: 46,
        sugars: 24,
        sodium: 20,
        cholesterol: 0,
        tags: ['Antioxidants', 'Low Sugar'],
        foodType: 'snack',
        allergens: [],
        ingredients: ['dark chocolate'],
        cookingMethod: 'none',
        spicyLevel: 0,
      },
      harga: 40000,
      stok: 100,
    },
    {
      id: '16',
      namaProduk: 'Banana',
      kategori: 'Fruits',
      gambar: '🍌',
      nilaiGizi: {
        calories: 89,
        protein: 1,
        fat: 0,
        carbs: 23,
        sugars: 12,
        sodium: 1,
        cholesterol: 0,
        tags: ['Potassium', 'Energy Boost'],
        foodType: 'fruit',
        allergens: [],
        ingredients: ['banana'],
        cookingMethod: 'none',
        spicyLevel: 0,
      },
      harga: 15000,
      stok: 100,
    },
    {
      id: '17',
      namaProduk: 'Broccoli',
      kategori: 'Vegetables',
      gambar: '🥦',
      nilaiGizi: {
        calories: 34,
        protein: 3,
        fat: 0,
        carbs: 7,
        sugars: 2,
        sodium: 33,
        cholesterol: 0,
        tags: ['Vitamin C', 'Fiber'],
        foodType: 'vegetable',
        allergens: [],
        ingredients: ['broccoli'],
        cookingMethod: 'boiled',
        spicyLevel: 0,
      },
      harga: 18000,
      stok: 100,
    },
    {
      id: '18',
      namaProduk: 'Quinoa',
      kategori: 'Grains',
      gambar: '🍚',
      nilaiGizi: {
        calories: 120,
        protein: 4,
        fat: 2,
        carbs: 21,
        sugars: 1,
        sodium: 7,
        cholesterol: 0,
        tags: ['Superfood', 'Complete Protein'],
        foodType: 'carb',
        allergens: [],
        ingredients: ['quinoa'],
        cookingMethod: 'boiled',
        spicyLevel: 0,
      },
      harga: 85000,
      stok: 100,
    },
    {
      id: '19',
      namaProduk: 'Lentils',
      kategori: 'Plant Protein',
      gambar: '🍲',
      nilaiGizi: {
        calories: 116,
        protein: 9,
        fat: 0,
        carbs: 20,
        sugars: 2,
        sodium: 2,
        cholesterol: 0,
        tags: ['Iron', 'High Fiber'],
        foodType: 'protein',
        allergens: [],
        ingredients: ['lentils'],
        cookingMethod: 'boiled',
        spicyLevel: 0,
      },
      harga: 35000,
      stok: 100,
    },
    {
      id: '20',
      namaProduk: 'Chia Seeds',
      kategori: 'Seeds',
      gambar: '🌰',
      nilaiGizi: {
        calories: 486,
        protein: 17,
        fat: 31,
        carbs: 42,
        sugars: 0,
        sodium: 16,
        cholesterol: 0,
        tags: ['Omega-3', 'Superfood'],
        foodType: 'fat',
        allergens: [],
        ingredients: ['chia seeds'],
        cookingMethod: 'none',
        spicyLevel: 0,
      },
      harga: 60000,
      stok: 100,
    },
    {
      id: '21',
      namaProduk: 'Fuji Apples',
      kategori: 'Fruits',
      gambar: '🍎',
      nilaiGizi: {
        calories: 52,
        protein: 0,
        fat: 0,
        carbs: 14,
        sugars: 10,
        sodium: 1,
        cholesterol: 0,
        tags: ['High Fiber', 'Low Calorie'],
        foodType: 'fruit',
        allergens: [],
        ingredients: ['apple'],
        cookingMethod: 'none',
        spicyLevel: 0,
      },
      harga: 35000,
      stok: 100,
    },
    {
      id: '22',
      namaProduk: 'Carrots',
      kategori: 'Vegetables',
      gambar: '🥕',
      nilaiGizi: {
        calories: 41,
        protein: 1,
        fat: 0,
        carbs: 10,
        sugars: 5,
        sodium: 69,
        cholesterol: 0,
        tags: ['Vitamin A', 'Beta Carotene'],
        foodType: 'vegetable',
        allergens: [],
        ingredients: ['carrot'],
        cookingMethod: 'none',
        spicyLevel: 0,
      },
      harga: 12000,
      stok: 100,
    },
    {
      id: '23',
      namaProduk: 'Whole Wheat Bread',
      kategori: 'Grains',
      gambar: '🍞',
      nilaiGizi: {
        calories: 80,
        protein: 4,
        fat: 1,
        carbs: 14,
        sugars: 1,
        sodium: 110,
        cholesterol: 0,
        tags: ['Whole Grain', 'Carbs'],
        foodType: 'carb',
        allergens: ['wheat'],
        ingredients: ['whole wheat bread'],
        cookingMethod: 'baked',
        spicyLevel: 0,
      },
      harga: 20000,
      stok: 100,
    },
    {
      id: '24',
      namaProduk: 'Lean Beef Mince',
      kategori: 'Meat',
      gambar: '🥩',
      nilaiGizi: {
        calories: 250,
        protein: 26,
        fat: 15,
        carbs: 0,
        sugars: 0,
        sodium: 66,
        cholesterol: 82,
        tags: ['Iron', 'High Protein'],
        foodType: 'protein',
        allergens: [],
        ingredients: ['beef'],
        cookingMethod: 'grilled',
        spicyLevel: 0,
      },
      harga: 95000,
      stok: 100,
    },
    {
      id: '25',
      namaProduk: 'Canned Tuna (Water)',
      kategori: 'Seafood',
      gambar: '🥫',
      nilaiGizi: {
        calories: 90,
        protein: 20,
        fat: 1,
        carbs: 0,
        sugars: 0,
        sodium: 210,
        cholesterol: 30,
        tags: ['Lean Protein', 'Low Calorie'],
        foodType: 'protein',
        allergens: ['fish'],
        ingredients: ['tuna'],
        cookingMethod: 'canned',
        spicyLevel: 0,
      },
      harga: 22000,
      stok: 100,
    },
    {
      id: '26',
      namaProduk: 'Garlic',
      kategori: 'Vegetables',
      gambar: '🧄',
      nilaiGizi: {
        calories: 149,
        protein: 6,
        fat: 0,
        carbs: 33,
        sugars: 1,
        sodium: 17,
        cholesterol: 0,
        tags: ['Immunity', 'Antioxidants'],
        foodType: 'spice',
        allergens: [],
        ingredients: ['garlic'],
        cookingMethod: 'none',
        spicyLevel: 0,
      },
      harga: 40000,
      stok: 100,
    },
    {
      id: '27',
      namaProduk: 'Edamame',
      kategori: 'Plant Protein',
      gambar: '🫛',
      nilaiGizi: {
        calories: 121,
        protein: 12,
        fat: 5,
        carbs: 11,
        sugars: 2,
        sodium: 6,
        cholesterol: 0,
        tags: ['Plant Protein', 'Snack'],
        foodType: 'protein',
        allergens: ['soy'],
        ingredients: ['edamame'],
        cookingMethod: 'boiled',
        spicyLevel: 0,
      },
      harga: 20000,
      stok: 100,
    },
    {
      id: '28',
      namaProduk: 'Tomatoes',
      kategori: 'Vegetables',
      gambar: '🍅',
      nilaiGizi: {
        calories: 18,
        protein: 1,
        fat: 0,
        carbs: 4,
        sugars: 2,
        sodium: 5,
        cholesterol: 0,
        tags: ['Lycopene', 'Vitamin C'],
        foodType: 'vegetable',
        allergens: [],
        ingredients: ['tomato'],
        cookingMethod: 'none',
        spicyLevel: 0,
      },
      harga: 14000,
      stok: 100,
    },
    {
      id: '29',
      namaProduk: 'Red Bell Pepper',
      kategori: 'Vegetables',
      gambar: '🫑',
      nilaiGizi: {
        calories: 31,
        protein: 1,
        fat: 0,
        carbs: 6,
        sugars: 4,
        sodium: 4,
        cholesterol: 0,
        tags: ['High Vitamin C', 'Low Calorie'],
        foodType: 'vegetable',
        allergens: [],
        ingredients: ['red bell pepper'],
        cookingMethod: 'none',
        spicyLevel: 0,
      },
      harga: 30000,
      stok: 100,
    },
    {
      id: '30',
      namaProduk: 'Low Fat Milk',
      kategori: 'Dairy',
      gambar: '🥛',
      nilaiGizi: {
        calories: 42,
        protein: 3,
        fat: 1,
        carbs: 5,
        sugars: 5,
        sodium: 44,
        cholesterol: 5,
        tags: ['Calcium', 'Vitamin D'],
        foodType: 'dairy',
        allergens: ['milk'],
        ingredients: ['milk'],
        cookingMethod: 'none',
        spicyLevel: 0,
      },
      harga: 25000,
      stok: 100,
    },
    {
      id: '31',
      namaProduk: 'Cheddar Cheese',
      kategori: 'Dairy',
      gambar: '🧀',
      nilaiGizi: {
        calories: 402,
        protein: 25,
        fat: 33,
        carbs: 1,
        sugars: 0,
        sodium: 621,
        cholesterol: 105,
        tags: ['High Fat', 'Calcium'],
        foodType: 'dairy',
        allergens: ['milk'],
        ingredients: ['cheese'],
        cookingMethod: 'none',
        spicyLevel: 0,
      },
      harga: 35000,
      stok: 100,
    },
    {
      id: '32',
      namaProduk: 'Peanut Butter (Unsweetened)',
      kategori: 'Nuts',
      gambar: '🥜',
      nilaiGizi: {
        calories: 588,
        protein: 25,
        fat: 50,
        carbs: 20,
        sugars: 4,
        sodium: 17,
        cholesterol: 0,
        tags: ['Healthy Fats', 'Protein'],
        foodType: 'fat',
        allergens: ['peanuts'],
        ingredients: ['peanuts'],
        cookingMethod: 'none',
        spicyLevel: 0,
      },
      harga: 45000,
      stok: 100,
    },
    {
      id: '33',
      namaProduk: 'Green Tea Bags',
      kategori: 'Beverages',
      gambar: '🍵',
      nilaiGizi: {
        calories: 0,
        protein: 0,
        fat: 0,
        carbs: 0,
        sugars: 0,
        sodium: 0,
        cholesterol: 0,
        tags: ['Zero Calorie', 'Antioxidants'],
        foodType: 'beverage',
        allergens: [],
        ingredients: ['green tea'],
        cookingMethod: 'boiled',
        spicyLevel: 0,
      },
      harga: 25000,
      stok: 100,
    },
    {
      id: '34',
      namaProduk: 'Black Coffee',
      kategori: 'Beverages',
      gambar: '☕',
      nilaiGizi: {
        calories: 2,
        protein: 0,
        fat: 0,
        carbs: 0,
        sugars: 0,
        sodium: 2,
        cholesterol: 0,
        tags: ['Zero Calorie', 'Caffeine'],
        foodType: 'beverage',
        allergens: [],
        ingredients: ['coffee beans'],
        cookingMethod: 'boiled',
        spicyLevel: 0,
      },
      harga: 35000,
      stok: 100,
    },
    {
      id: '35',
      namaProduk: 'Oranges',
      kategori: 'Fruits',
      gambar: '🍊',
      nilaiGizi: {
        calories: 43,
        protein: 1,
        fat: 0,
        carbs: 12,
        sugars: 9,
        sodium: 0,
        cholesterol: 0,
        tags: ['Vitamin C', 'Immunity'],
        foodType: 'fruit',
        allergens: [],
        ingredients: ['orange'],
        cookingMethod: 'none',
        spicyLevel: 0,
      },
      harga: 25000,
      stok: 100,
    },
    {
      id: '36',
      namaProduk: 'Dragon Fruit',
      kategori: 'Fruits',
      gambar: '🍉',
      nilaiGizi: {
        calories: 60,
        protein: 1,
        fat: 1,
        carbs: 13,
        sugars: 8,
        sodium: 0,
        cholesterol: 0,
        tags: ['Antioxidants', 'Hydration'],
        foodType: 'fruit',
        allergens: [],
        ingredients: ['dragon fruit'],
        cookingMethod: 'none',
        spicyLevel: 0,
      },
      harga: 30000,
      stok: 100,
    },
    {
      id: '37',
      namaProduk: 'Unsalted Butter',
      kategori: 'Fats',
      gambar: '🧈',
      nilaiGizi: {
        calories: 717,
        protein: 1,
        fat: 81,
        carbs: 0,
        sugars: 0,
        sodium: 11,
        cholesterol: 215,
        tags: ['High Saturated Fat', 'Baking'],
        foodType: 'fat',
        allergens: ['milk'],
        ingredients: ['butter'],
        cookingMethod: 'none',
        spicyLevel: 0,
      },
      harga: 55000,
      stok: 100,
    },
    {
      id: '38',
      namaProduk: 'Baked Potato Chips',
      kategori: 'Snacks',
      gambar: '🥔',
      nilaiGizi: {
        calories: 400,
        protein: 4,
        fat: 14,
        carbs: 65,
        sugars: 1,
        sodium: 400,
        cholesterol: 0,
        tags: ['Carbs', 'Sodium'],
        foodType: 'snack',
        allergens: [],
        ingredients: ['potato', 'oil', 'salt'],
        cookingMethod: 'baked',
        spicyLevel: 0,
      },
      harga: 15000,
      stok: 100,
    },
    {
      id: '39',
      namaProduk: 'Himalayan Pink Salt',
      kategori: 'Spices',
      gambar: '🧂',
      nilaiGizi: {
        calories: 0,
        protein: 0,
        fat: 0,
        carbs: 0,
        sugars: 0,
        sodium: 38000,
        cholesterol: 0,
        tags: ['Minerals', 'Zero Calorie'],
        foodType: 'spice',
        allergens: [],
        ingredients: ['salt'],
        cookingMethod: 'none',
        spicyLevel: 0,
      },
      harga: 50000,
      stok: 100,
    },
    {
      id: '40',
      namaProduk: 'Red Onion',
      kategori: 'Vegetables',
      gambar: '🧅',
      nilaiGizi: {
        calories: 40,
        protein: 1,
        fat: 0,
        carbs: 9,
        sugars: 4,
        sodium: 4,
        cholesterol: 0,
        tags: ['Flavor', 'Antioxidants'],
        foodType: 'vegetable',
        allergens: [],
        ingredients: ['red onion'],
        cookingMethod: 'none',
        spicyLevel: 0,
      },
      harga: 28000,
      stok: 100,
    },
    {
      id: '41',
      namaProduk: 'Red Chili',
      kategori: 'Vegetables',
      gambar: '🌶️',
      nilaiGizi: {
        calories: 40,
        protein: 2,
        fat: 0,
        carbs: 9,
        sugars: 5,
        sodium: 9,
        cholesterol: 0,
        tags: ['Capsaicin', 'Spicy'],
        foodType: 'vegetable',
        allergens: [],
        ingredients: ['red chili'],
        cookingMethod: 'none',
        spicyLevel: 3,
      },
      harga: 40000,
      stok: 100,
    },
    {
      id: '42',
      namaProduk: 'Tilapia Fish',
      kategori: 'Seafood',
      gambar: '🐠',
      nilaiGizi: {
        calories: 96,
        protein: 20,
        fat: 2,
        carbs: 0,
        sugars: 0,
        sodium: 52,
        cholesterol: 50,
        tags: ['Lean Protein', 'Mild Flavor'],
        foodType: 'protein',
        allergens: ['fish'],
        ingredients: ['tilapia'],
        cookingMethod: 'grilled',
        spicyLevel: 0,
      },
      harga: 30000,
      stok: 100,
    },
    {
      id: '43',
      namaProduk: 'Strawberry Yogurt',
      kategori: 'Dairy',
      gambar: '🍓',
      nilaiGizi: {
        calories: 95,
        protein: 4,
        fat: 1,
        carbs: 16,
        sugars: 15,
        sodium: 45,
        cholesterol: 5,
        tags: ['Added Sugar', 'Probiotic'],
        foodType: 'dairy',
        allergens: ['milk'],
        ingredients: ['yogurt', 'strawberry'],
        cookingMethod: 'none',
        spicyLevel: 0,
      },
      harga: 15000,
      stok: 100,
    },
    {
      id: '44',
      namaProduk: 'Mung Beans',
      kategori: 'Plant Protein',
      gambar: '🟢',
      nilaiGizi: {
        calories: 347,
        protein: 24,
        fat: 1,
        carbs: 63,
        sugars: 7,
        sodium: 15,
        cholesterol: 0,
        tags: ['Folate', 'Fiber'],
        foodType: 'protein',
        allergens: [],
        ingredients: ['mung beans'],
        cookingMethod: 'boiled',
        spicyLevel: 0,
      },
      harga: 20000,
      stok: 100,
    },
    {
      id: '45',
      namaProduk: 'Ajwa Dates',
      kategori: 'Fruits',
      gambar: '🌴',
      nilaiGizi: {
        calories: 277,
        protein: 2,
        fat: 0,
        carbs: 75,
        sugars: 66,
        sodium: 1,
        cholesterol: 0,
        tags: ['High Sugar', 'Energy'],
        foodType: 'fruit',
        allergens: [],
        ingredients: ['dates'],
        cookingMethod: 'none',
        spicyLevel: 0,
      },
      harga: 120000,
      stok: 100,
    },
    {
      id: '46',
      namaProduk: 'Shirataki Noodles',
      kategori: 'Grains',
      gambar: '🍝',
      nilaiGizi: {
        calories: 9,
        protein: 0,
        fat: 0,
        carbs: 3,
        sugars: 0,
        sodium: 0,
        cholesterol: 0,
        tags: ['Zero Calorie', 'Keto'],
        foodType: 'carb',
        allergens: [],
        ingredients: ['konjac'],
        cookingMethod: 'boiled',
        spicyLevel: 0,
      },
      harga: 12000,
      stok: 100,
    },
    {
      id: '47',
      namaProduk: 'Sunflower Seeds',
      kategori: 'Seeds',
      gambar: '🌻',
      nilaiGizi: {
        calories: 584,
        protein: 21,
        fat: 51,
        carbs: 20,
        sugars: 3,
        sodium: 9,
        cholesterol: 0,
        tags: ['Vitamin E', 'Snack'],
        foodType: 'fat',
        allergens: [],
        ingredients: ['sunflower seeds'],
        cookingMethod: 'none',
        spicyLevel: 0,
      },
      harga: 25000,
      stok: 100,
    },
    {
      id: '48',
      namaProduk: 'Kidney Beans',
      kategori: 'Plant Protein',
      gambar: '🫘',
      nilaiGizi: {
        calories: 333,
        protein: 24,
        fat: 1,
        carbs: 60,
        sugars: 2,
        sodium: 24,
        cholesterol: 0,
        tags: ['Iron', 'High Protein'],
        foodType: 'protein',
        allergens: [],
        ingredients: ['kidney beans'],
        cookingMethod: 'boiled',
        spicyLevel: 0,
      },
      harga: 22000,
      stok: 100,
    },
    {
      id: '49',
      namaProduk: 'Palm Sugar',
      kategori: 'Sweeteners',
      gambar: '🍯',
      nilaiGizi: {
        calories: 380,
        protein: 0,
        fat: 0,
        carbs: 98,
        sugars: 98,
        sodium: 2,
        cholesterol: 0,
        tags: ['High Sugar', 'Low GI'],
        foodType: 'sweetener',
        allergens: [],
        ingredients: ['palm sugar'],
        cookingMethod: 'none',
        spicyLevel: 0,
      },
      harga: 30000,
      stok: 100,
    },
    {
      id: '50',
      namaProduk: 'Mustard Greens',
      kategori: 'Vegetables',
      gambar: '🥬',
      nilaiGizi: {
        calories: 13,
        protein: 1,
        fat: 0,
        carbs: 3,
        sugars: 1,
        sodium: 10,
        cholesterol: 0,
        tags: ['Vitamin K', 'Low Calorie'],
        foodType: 'vegetable',
        allergens: [],
        ingredients: ['mustard greens'],
        cookingMethod: 'boiled',
        spicyLevel: 0,
      },
      harga: 5000,
      stok: 100,
    },
  ];

  for (const p of mockProducts) {
    await prisma.produkMakanan.create({
      data: {
        id: p.id,
        namaProduk: p.namaProduk,
        kategori: p.kategori,
        gambar: p.gambar,
        nilaiGizi: p.nilaiGizi,
        harga: p.harga,
        stok: p.stok,
      },
    });
  }

  console.log('Seeding Admin account...');
  try {
    const { auth } = await import('../src/lib/auth');

    // Check if admin already exists
    const existingAdmin = await prisma.user.findUnique({
      where: { email: 'admin@nutriscale.com' },
    });

    if (!existingAdmin) {
      const res = await auth.api.signUpEmail({
        body: {
          email: 'admin@nutriscale.com',
          password: 'adminpassword123',
          name: 'Super Admin',
        },
      });

      if (res?.user?.id) {
        await prisma.user.update({
          where: { id: res.user.id },
          data: {
            role: 'admin',
            emailVerified: true,
          },
        });
        console.log(
          'Admin account created successfully. (admin@nutriscale.com / adminpassword123)',
        );
      } else {
        console.log('Failed to create admin account via auth API.');
      }
    } else {
      console.log('Admin account already exists.');
    }
  } catch (error) {
    console.error('Error seeding admin account:', error);
  }

  console.log('Seed completed.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
