import 'dotenv/config';

import prisma from '../src/lib/prisma';

async function main() {
  console.log('Clearing existing data...');
  await prisma.cartItem.deleteMany({});
  await prisma.cart.deleteMany({});
  await prisma.mealPlanProduk.deleteMany({});
  await prisma.orderItem.deleteMany({});
  await prisma.produkMakanan.deleteMany({});
  await prisma.mealPlan.deleteMany({});
  await prisma.riwayatAnalisis.deleteMany({});
  await prisma.profilKesehatan.deleteMany({});

  console.log('Seeding products...');
  const mockProducts = [
    {
      id: '1',
      namaProduk: 'Organic Brown Rice',
      kategori: 'Grains',
      gambar: '🌾',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Low Sodium', 'Whole Grain'],
        calories: 110,
        protein: 3,
      },
      harga: 25000,
      stok: 100,
    },
    {
      id: '2',
      namaProduk: 'Fresh Chicken Breast',
      kategori: 'Meat',
      gambar: '🍗',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: false,
        tags: ['High Protein'],
        calories: 165,
        protein: 31,
      },
      harga: 45000,
      stok: 100,
    },
    {
      id: '3',
      namaProduk: 'Greek Yogurt',
      kategori: 'Dairy',
      gambar: '🥛',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Low Fat', 'Probiotic'],
        calories: 59,
        protein: 10,
      },
      harga: 20000,
      stok: 100,
    },
    {
      id: '4',
      namaProduk: 'Salmon Fillet',
      kategori: 'Seafood',
      gambar: '🐟',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: false,
        tags: ['Omega-3', 'High Protein'],
        calories: 208,
        protein: 22,
      },
      harga: 75000,
      stok: 100,
    },
    {
      id: '5',
      namaProduk: 'Sweet Potato',
      kategori: 'Vegetables',
      gambar: '🍠',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: false,
        tags: ['High Fiber', 'Low Fat'],
        calories: 86,
        protein: 2,
      },
      harga: 15000,
      stok: 100,
    },
    {
      id: '6',
      namaProduk: 'Honey',
      kategori: 'Sweeteners',
      gambar: '🍯',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Natural Sugar', 'High Sugar'],
        calories: 64,
        protein: 0,
      },
      harga: 30000,
      stok: 100,
    },
    {
      id: '7',
      namaProduk: 'Avocado',
      kategori: 'Fruits',
      gambar: '🥑',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Healthy Fats', 'High Fiber'],
        calories: 160,
        protein: 2,
      },
      harga: 25000,
      stok: 100,
    },
    {
      id: '8',
      namaProduk: 'Almonds',
      kategori: 'Nuts',
      gambar: '🥜',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Vitamin E', 'Healthy Fats'],
        calories: 579,
        protein: 21,
      },
      harga: 65000,
      stok: 100,
    },
    {
      id: '9',
      namaProduk: 'Spinach',
      kategori: 'Vegetables',
      gambar: '🥬',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Iron', 'Vitamins'],
        calories: 23,
        protein: 3,
      },
      harga: 10000,
      stok: 100,
    },
    {
      id: '10',
      namaProduk: 'Tofu',
      kategori: 'Plant Protein',
      gambar: '🧊',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Calcium', 'Vegan'],
        calories: 76,
        protein: 8,
      },
      harga: 8000,
      stok: 100,
    },
    {
      id: '11',
      namaProduk: 'Tempeh',
      kategori: 'Plant Protein',
      gambar: '🧆',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Fermented', 'High Protein'],
        calories: 193,
        protein: 19,
      },
      harga: 10000,
      stok: 100,
    },
    {
      id: '12',
      namaProduk: 'Eggs',
      kategori: 'Dairy/Egg',
      gambar: '🥚',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Complete Protein', 'Choline'],
        calories: 70,
        protein: 6,
      },
      harga: 28000,
      stok: 100,
    },
    {
      id: '13',
      namaProduk: 'Oatmeal',
      kategori: 'Grains',
      gambar: '🥣',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Beta Glucan', 'High Fiber'],
        calories: 150,
        protein: 5,
      },
      harga: 32000,
      stok: 100,
    },
    {
      id: '14',
      namaProduk: 'Extra Virgin Olive Oil',
      kategori: 'Oils',
      gambar: '🫒',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Heart Healthy', 'Antioxidants'],
        calories: 884,
        protein: 0,
      },
      harga: 95000,
      stok: 100,
    },
    {
      id: '15',
      namaProduk: 'Dark Chocolate (70%)',
      kategori: 'Snacks',
      gambar: '🍫',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Antioxidants', 'Low Sugar'],
        calories: 598,
        protein: 8,
      },
      harga: 40000,
      stok: 100,
    },
    {
      id: '16',
      namaProduk: 'Banana',
      kategori: 'Fruits',
      gambar: '🍌',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Potassium', 'Energy Boost'],
        calories: 89,
        protein: 1,
      },
      harga: 15000,
      stok: 100,
    },
    {
      id: '17',
      namaProduk: 'Broccoli',
      kategori: 'Vegetables',
      gambar: '🥦',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Vitamin C', 'Fiber'],
        calories: 34,
        protein: 3,
      },
      harga: 18000,
      stok: 100,
    },
    {
      id: '18',
      namaProduk: 'Quinoa',
      kategori: 'Grains',
      gambar: '🍚',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Superfood', 'Complete Protein'],
        calories: 120,
        protein: 4,
      },
      harga: 85000,
      stok: 100,
    },
    {
      id: '19',
      namaProduk: 'Lentils',
      kategori: 'Plant Protein',
      gambar: '🍲',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Iron', 'High Fiber'],
        calories: 116,
        protein: 9,
      },
      harga: 35000,
      stok: 100,
    },
    {
      id: '20',
      namaProduk: 'Chia Seeds',
      kategori: 'Seeds',
      gambar: '🌰',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Omega-3', 'Superfood'],
        calories: 486,
        protein: 17,
      },
      harga: 60000,
      stok: 100,
    },
    {
      id: '21',
      namaProduk: 'Fuji Apples',
      kategori: 'Fruits',
      gambar: '🍎',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['High Fiber', 'Low Calorie'],
        calories: 52,
        protein: 0,
      },
      harga: 35000,
      stok: 100,
    },
    {
      id: '22',
      namaProduk: 'Carrots',
      kategori: 'Vegetables',
      gambar: '🥕',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Vitamin A', 'Beta Carotene'],
        calories: 41,
        protein: 1,
      },
      harga: 12000,
      stok: 100,
    },
    {
      id: '23',
      namaProduk: 'Whole Wheat Bread',
      kategori: 'Grains',
      gambar: '🍞',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: false,
        tags: ['Whole Grain', 'Carbs'],
        calories: 80,
        protein: 4,
      },
      harga: 20000,
      stok: 100,
    },
    {
      id: '24',
      namaProduk: 'Lean Beef Mince',
      kategori: 'Meat',
      gambar: '🥩',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: false,
        tags: ['Iron', 'High Protein'],
        calories: 250,
        protein: 26,
      },
      harga: 95000,
      stok: 100,
    },
    {
      id: '25',
      namaProduk: 'Canned Tuna (Water)',
      kategori: 'Seafood',
      gambar: '🥫',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Lean Protein', 'Low Calorie'],
        calories: 90,
        protein: 20,
      },
      harga: 22000,
      stok: 100,
    },
    {
      id: '26',
      namaProduk: 'Garlic',
      kategori: 'Vegetables',
      gambar: '🧄',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Immunity', 'Antioxidants'],
        calories: 149,
        protein: 6,
      },
      harga: 40000,
      stok: 100,
    },
    {
      id: '27',
      namaProduk: 'Edamame',
      kategori: 'Plant Protein',
      gambar: '🫛',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Plant Protein', 'Snack'],
        calories: 121,
        protein: 12,
      },
      harga: 20000,
      stok: 100,
    },
    {
      id: '28',
      namaProduk: 'Tomatoes',
      kategori: 'Vegetables',
      gambar: '🍅',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Lycopene', 'Vitamin C'],
        calories: 18,
        protein: 1,
      },
      harga: 14000,
      stok: 100,
    },
    {
      id: '29',
      namaProduk: 'Red Bell Pepper',
      kategori: 'Vegetables',
      gambar: '🫑',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['High Vitamin C', 'Low Calorie'],
        calories: 31,
        protein: 1,
      },
      harga: 30000,
      stok: 100,
    },
    {
      id: '30',
      namaProduk: 'Low Fat Milk',
      kategori: 'Dairy',
      gambar: '🥛',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: false,
        tags: ['Calcium', 'Vitamin D'],
        calories: 42,
        protein: 3,
      },
      harga: 25000,
      stok: 100,
    },
    {
      id: '31',
      namaProduk: 'Cheddar Cheese',
      kategori: 'Dairy',
      gambar: '🧀',
      nilaiGizi: {
        healthSafe: false,
        aiRecommended: false,
        tags: ['High Fat', 'Calcium'],
        calories: 402,
        protein: 25,
      },
      harga: 35000,
      stok: 100,
    },
    {
      id: '32',
      namaProduk: 'Peanut Butter (Unsweetened)',
      kategori: 'Nuts',
      gambar: '🥜',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Healthy Fats', 'Protein'],
        calories: 588,
        protein: 25,
      },
      harga: 45000,
      stok: 100,
    },
    {
      id: '33',
      namaProduk: 'Green Tea Bags',
      kategori: 'Beverages',
      gambar: '🍵',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Zero Calorie', 'Antioxidants'],
        calories: 0,
        protein: 0,
      },
      harga: 25000,
      stok: 100,
    },
    {
      id: '34',
      namaProduk: 'Black Coffee',
      kategori: 'Beverages',
      gambar: '☕',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: false,
        tags: ['Zero Calorie', 'Caffeine'],
        calories: 2,
        protein: 0,
      },
      harga: 35000,
      stok: 100,
    },
    {
      id: '35',
      namaProduk: 'Oranges',
      kategori: 'Fruits',
      gambar: '🍊',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Vitamin C', 'Immunity'],
        calories: 43,
        protein: 1,
      },
      harga: 25000,
      stok: 100,
    },
    {
      id: '36',
      namaProduk: 'Dragon Fruit',
      kategori: 'Fruits',
      gambar: '🍉',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Antioxidants', 'Hydration'],
        calories: 60,
        protein: 1,
      },
      harga: 30000,
      stok: 100,
    },
    {
      id: '37',
      namaProduk: 'Unsalted Butter',
      kategori: 'Fats',
      gambar: '🧈',
      nilaiGizi: {
        healthSafe: false,
        aiRecommended: false,
        tags: ['High Saturated Fat', 'Baking'],
        calories: 717,
        protein: 1,
      },
      harga: 55000,
      stok: 100,
    },
    {
      id: '38',
      namaProduk: 'Baked Potato Chips',
      kategori: 'Snacks',
      gambar: '🥔',
      nilaiGizi: {
        healthSafe: false,
        aiRecommended: false,
        tags: ['Carbs', 'Sodium'],
        calories: 400,
        protein: 4,
      },
      harga: 15000,
      stok: 100,
    },
    {
      id: '39',
      namaProduk: 'Himalayan Pink Salt',
      kategori: 'Spices',
      gambar: '🧂',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: false,
        tags: ['Minerals', 'Zero Calorie'],
        calories: 0,
        protein: 0,
      },
      harga: 50000,
      stok: 100,
    },
    {
      id: '40',
      namaProduk: 'Red Onion',
      kategori: 'Vegetables',
      gambar: '🧅',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Flavor', 'Antioxidants'],
        calories: 40,
        protein: 1,
      },
      harga: 28000,
      stok: 100,
    },
    {
      id: '41',
      namaProduk: 'Red Chili',
      kategori: 'Vegetables',
      gambar: '🌶️',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: false,
        tags: ['Capsaicin', 'Spicy'],
        calories: 40,
        protein: 2,
      },
      harga: 40000,
      stok: 100,
    },
    {
      id: '42',
      namaProduk: 'Tilapia Fish',
      kategori: 'Seafood',
      gambar: '🐠',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Lean Protein', 'Mild Flavor'],
        calories: 96,
        protein: 20,
      },
      harga: 30000,
      stok: 100,
    },
    {
      id: '43',
      namaProduk: 'Strawberry Yogurt',
      kategori: 'Dairy',
      gambar: '🍓',
      nilaiGizi: {
        healthSafe: false,
        aiRecommended: false,
        tags: ['Added Sugar', 'Probiotic'],
        calories: 95,
        protein: 4,
      },
      harga: 15000,
      stok: 100,
    },
    {
      id: '44',
      namaProduk: 'Mung Beans',
      kategori: 'Plant Protein',
      gambar: '🟢',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Folate', 'Fiber'],
        calories: 347,
        protein: 24,
      },
      harga: 20000,
      stok: 100,
    },
    {
      id: '45',
      namaProduk: 'Ajwa Dates',
      kategori: 'Fruits',
      gambar: '🌴',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: false,
        tags: ['High Sugar', 'Energy'],
        calories: 277,
        protein: 2,
      },
      harga: 120000,
      stok: 100,
    },
    {
      id: '46',
      namaProduk: 'Shirataki Noodles',
      kategori: 'Grains',
      gambar: '🍝',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Zero Calorie', 'Keto'],
        calories: 9,
        protein: 0,
      },
      harga: 12000,
      stok: 100,
    },
    {
      id: '47',
      namaProduk: 'Sunflower Seeds',
      kategori: 'Seeds',
      gambar: '🌻',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Vitamin E', 'Snack'],
        calories: 584,
        protein: 21,
      },
      harga: 25000,
      stok: 100,
    },
    {
      id: '48',
      namaProduk: 'Kidney Beans',
      kategori: 'Plant Protein',
      gambar: '🫘',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Iron', 'High Protein'],
        calories: 333,
        protein: 24,
      },
      harga: 22000,
      stok: 100,
    },
    {
      id: '49',
      namaProduk: 'Palm Sugar',
      kategori: 'Sweeteners',
      gambar: '🍯',
      nilaiGizi: {
        healthSafe: false,
        aiRecommended: false,
        tags: ['High Sugar', 'Low GI'],
        calories: 380,
        protein: 0,
      },
      harga: 30000,
      stok: 100,
    },
    {
      id: '50',
      namaProduk: 'Mustard Greens',
      kategori: 'Vegetables',
      gambar: '🥬',
      nilaiGizi: {
        healthSafe: true,
        aiRecommended: true,
        tags: ['Vitamin K', 'Low Calorie'],
        calories: 13,
        protein: 1,
      },
      harga: 5000,
      stok: 100,
    },
  ];

  for (const p of mockProducts) {
    await prisma.produkMakanan.create({
      data: {
        id: p.id,
        namaProduk: p.namaProduk,
        kategori: p.kategori,
        gambar: p.gambar,
        nilaiGizi: p.nilaiGizi,
        harga: p.harga,
        stok: p.stok,
      },
    });
  }

  console.log('Seeding Admin account...');
  try {
    const { auth } = await import('../src/lib/auth');

    // Check if admin already exists
    const existingAdmin = await prisma.user.findUnique({
      where: { email: 'admin@nutriscale.com' },
    });

    if (!existingAdmin) {
      const res = await auth.api.signUpEmail({
        body: {
          email: 'admin@nutriscale.com',
          password: 'adminpassword123',
          name: 'Super Admin',
        },
      });

      if (res?.user?.id) {
        await prisma.user.update({
          where: { id: res.user.id },
          data: {
            role: 'admin',
            emailVerified: true,
          },
        });
        console.log(
          'Admin account created successfully. (admin@nutriscale.com / adminpassword123)',
        );
      } else {
        console.log('Failed to create admin account via auth API.');
      }
    } else {
      console.log('Admin account already exists.');
    }
  } catch (error) {
    console.error('Error seeding admin account:', error);
  }

  console.log('Seed completed.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
